### ISSUE TITLE
README doesn't explain how to use this boilerplate

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/website-boilerplate#39]
The README gives instructions to install cookiecutter from pip and then links to this repo. Some guidance on how to use this would be good.

**Comment by jpmartinspt** [comment]
@steverydz It does not link to the repo, it says `cookiecutter <this_repo_url>`. That when executed will prompt you a bunch of questions and create the folder structure, but those are basically the two steps you need to do to create a site from the boilerplate.

**Comment by steverydz** [comment]
@jpmartinspt ah cool - I'll close this in that case
